# Generated by Django 5.2.1 on 2025-06-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookWishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.CharField(choices=[('100 diagnostic dilemmas in clinical medicine', '100 diagnostic dilemmas in clinical medicine'), ('100 cases in obstetrics and gynaecology', '100 cases in obstetrics and gynaecology'), ('100 cases in accute medicine', '100 cases in accute medicine')], default='100 diagnostic dilemmas in clinical medicine', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name_plural': 'Book Wishes',
            },
        ),
    ]
