# Generated by Django 5.2.1 on 2025-06-19 05:42

import anniversary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=anniversary.models.get_image_upload_path)),
                ('Anniversary_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary', to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctor Anniversary',
                'verbose_name_plural': 'Doctor Anniversary',
                'db_table': 'dr_anniversary',
            },
        ),
    ]
