# Generated by Django 5.2.1 on 2025-06-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anniversary',
            old_name='Anniversary_date',
            new_name='anniversary_date',
        ),
    ]
