# Generated by Django 5.2.1 on 2025-06-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrGiftCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift', models.CharField(choices=[('Pureit Classic 23 L', 'Pureit Classic 23 L'), ('Smart Watch Fastrack Reflex Rave FX', 'Smart Watch Fastrack Reflex Rave FX'), ('Kiam Marble Coated 7 pc Set', 'Kiam Marble Coated 7 pc Set'), ('Philips Blender 450W Daily Collection (HR2058/91)', 'Philips Blender 450W Daily Collection (HR2058/91)'), ('International Scientific Conference Registration', 'International Scientific Conference Registration')], default='Pureit Classic 23 L', max_length=255)),
                ('conference_image', models.ImageField(blank=True, null=True, upload_to='conference_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_gift_catalogs', to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctor Gift Catalog',
                'verbose_name_plural': 'Doctor Gift Catalogs',
                'db_table': 'dr_gift_catalogs',
            },
        ),
    ]
