# Generated by Django 5.2.1 on 2025-06-19 03:32

import dr_gift_catalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_gift_catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drgiftcatalog',
            name='conference_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=dr_gift_catalogs.models.get_image_upload_path),
        ),
    ]
