# Generated by Django 5.1.1 on 2025-07-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='chamber',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctors_data.doctor'),
        ),
    ]
