# Generated by Django 5.2.1 on 2025-07-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dr_id", models.CharField(max_length=20, unique=True)),
                ("dr_name", models.CharField(max_length=100)),
                ("dr_phone", models.CharField(max_length=15)),
                ("dr_address", models.CharField(max_length=255)),
                ("dr_specialty", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_opinions",
                        to="core.territory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Opinion",
                "verbose_name_plural": "Doctor Opinions",
                "db_table": "doctor_opinion",
            },
        ),
        migrations.CreateModel(
            name="DoctorIndication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indication_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor_opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications",
                        to="doctors_opinion.doctoropinion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Indication",
                "verbose_name_plural": "Doctor Indications",
                "db_table": "doctor_indication",
            },
        ),
    ]
