# Generated by Django 5.2.4 on 2025-07-07 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dr_address', models.CharField(blank=True, max_length=200, null=True)),
                ('rm_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_flower_plant', models.CharField(blank=True, max_length=30, null=True)),
                ('second_flower_plant', models.CharField(blank=True, max_length=30, null=True)),
                ('third_flower_plant', models.CharField(blank=True, max_length=30, null=True)),
                ('first_medicine_plant', models.CharField(blank=True, max_length=30, null=True)),
                ('second_medicine_plant', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
        ),
    ]
