# Generated by Django 5.2.4 on 2025-07-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_corner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greencorner',
            options={'verbose_name': 'Green Corner', 'verbose_name_plural': 'Green Corner'},
        ),
        migrations.AlterModelTable(
            name='greencorner',
            table='green_corner',
        ),
    ]
