# Generated by Django 5.2.4 on 2025-07-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_corner', '0002_alter_greencorner_options_alter_greencorner_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greencorner',
            old_name='first_medicine_plant',
            new_name='first_medicinal_plant',
        ),
        migrations.RenameField(
            model_name='greencorner',
            old_name='second_medicine_plant',
            new_name='second_medicinal_plant',
        ),
    ]
